package com.chaoxiang.entity.dao;

import android.database.sqlite.SQLiteDatabase;

import com.chaoxiang.entity.chat.IMAddFriend;
import com.chaoxiang.entity.chat.IMAudioFail;
import com.chaoxiang.entity.chat.IMCallLog;
import com.chaoxiang.entity.chat.IMGroupChat;
import com.chaoxiang.entity.chat.IMKeFu;
import com.chaoxiang.entity.chat.IMMessage;
import com.chaoxiang.entity.chat.IMVoiceGroup;
import com.chaoxiang.entity.chat.IMWorkCircle;
import com.chaoxiang.entity.conversation.IMConversation;
import com.chaoxiang.entity.group.IMGroup;
import com.chaoxiang.entity.pushuser.IMUser;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession
{

    private final DaoConfig iMUserDaoConfig;
    private final DaoConfig iMGroupDaoConfig;
    private final DaoConfig iMGroupChatDaoConfig;
    private final DaoConfig iMMessageDaoConfig;
    private final DaoConfig iMConversationDaoConfig;
    private final DaoConfig iMAudioFailDaoConfig;
    private final DaoConfig iMVoiceGroupDaoConfig;
    private final DaoConfig iMCallLogDaoConfig;
    private final DaoConfig iMAddFriendDaoConfig;
    private final DaoConfig iMKeFuDaoConfig;
    private final DaoConfig iMWorkCircleDaoConfig;

    private final IMUserDao iMUserDao;
    private final IMGroupDao iMGroupDao;
    private final IMGroupChatDao iMGroupChatDao;
    private final IMMessageDao iMMessageDao;
    private final IMConversationDao iMConversationDao;
    private final IMAudioFailDao iMAudioFailDao;
    private final IMVoiceGroupDao iMVoiceGroupDao;
    private final IMCallLogDao iMCallLogDao;
    private final IMAddFriendDao iMAddFriendDao;
    private final IMKeFuDao iMKeFuDao;
    private final IMWorkCircleDao iMWorkCircleDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap)
    {
        super(db);

        iMUserDaoConfig = daoConfigMap.get(IMUserDao.class).clone();
        iMUserDaoConfig.initIdentityScope(type);

        iMGroupDaoConfig = daoConfigMap.get(IMGroupDao.class).clone();
        iMGroupDaoConfig.initIdentityScope(type);

        iMGroupChatDaoConfig = daoConfigMap.get(IMGroupChatDao.class).clone();
        iMGroupChatDaoConfig.initIdentityScope(type);

        iMMessageDaoConfig = daoConfigMap.get(IMMessageDao.class).clone();
        iMMessageDaoConfig.initIdentityScope(type);

        iMConversationDaoConfig = daoConfigMap.get(IMConversationDao.class).clone();
        iMConversationDaoConfig.initIdentityScope(type);

        iMAudioFailDaoConfig = daoConfigMap.get(IMAudioFailDao.class).clone();
        iMAudioFailDaoConfig.initIdentityScope(type);

        iMVoiceGroupDaoConfig = daoConfigMap.get(IMVoiceGroupDao.class).clone();
        iMVoiceGroupDaoConfig.initIdentityScope(type);

        iMCallLogDaoConfig = daoConfigMap.get(IMCallLogDao.class).clone();
        iMCallLogDaoConfig.initIdentityScope(type);

        iMAddFriendDaoConfig = daoConfigMap.get(IMAddFriendDao.class).clone();
        iMAddFriendDaoConfig.initIdentityScope(type);

        iMKeFuDaoConfig = daoConfigMap.get(IMKeFuDao.class).clone();
        iMKeFuDaoConfig.initIdentityScope(type);

        iMWorkCircleDaoConfig = daoConfigMap.get(IMWorkCircleDao.class).clone();
        iMWorkCircleDaoConfig.initIdentityScope(type);

        iMUserDao = new IMUserDao(iMUserDaoConfig, this);
        iMGroupDao = new IMGroupDao(iMGroupDaoConfig, this);
        iMGroupChatDao = new IMGroupChatDao(iMGroupChatDaoConfig, this);
        iMMessageDao = new IMMessageDao(iMMessageDaoConfig, this);
        iMConversationDao = new IMConversationDao(iMConversationDaoConfig, this);
        iMAudioFailDao = new IMAudioFailDao(iMAudioFailDaoConfig, this);
        iMVoiceGroupDao = new IMVoiceGroupDao(iMVoiceGroupDaoConfig, this);
        iMCallLogDao = new IMCallLogDao(iMCallLogDaoConfig, this);
        iMAddFriendDao = new IMAddFriendDao(iMAddFriendDaoConfig, this);
        iMKeFuDao = new IMKeFuDao(iMKeFuDaoConfig, this);
        iMWorkCircleDao = new IMWorkCircleDao(iMWorkCircleDaoConfig, this);

        registerDao(IMUser.class, iMUserDao);
        registerDao(IMGroup.class, iMGroupDao);
        registerDao(IMGroupChat.class, iMGroupChatDao);
        registerDao(IMMessage.class, iMMessageDao);
        registerDao(IMConversation.class, iMConversationDao);
        registerDao(IMAudioFail.class, iMAudioFailDao);
        registerDao(IMVoiceGroup.class, iMVoiceGroupDao);
        registerDao(IMCallLog.class, iMCallLogDao);
        registerDao(IMAddFriend.class, iMAddFriendDao);
        registerDao(IMKeFu.class, iMKeFuDao);
        registerDao(IMWorkCircle.class, iMWorkCircleDao);
    }

    public void clear()
    {
        iMUserDaoConfig.getIdentityScope().clear();
        iMGroupDaoConfig.getIdentityScope().clear();
        iMGroupChatDaoConfig.getIdentityScope().clear();
        iMMessageDaoConfig.getIdentityScope().clear();
        iMConversationDaoConfig.getIdentityScope().clear();
        iMAudioFailDaoConfig.getIdentityScope().clear();
        iMVoiceGroupDaoConfig.getIdentityScope().clear();
        iMCallLogDaoConfig.getIdentityScope().clear();
        iMAddFriendDaoConfig.getIdentityScope().clear();
        iMKeFuDaoConfig.getIdentityScope().clear();
        iMWorkCircleDaoConfig.getIdentityScope().clear();
    }

    public IMUserDao getIMUserDao()
    {
        return iMUserDao;
    }

    public IMGroupDao getIMGroupDao()
    {
        return iMGroupDao;
    }

    public IMGroupChatDao getIMGroupChatDao()
    {
        return iMGroupChatDao;
    }

    public IMMessageDao getIMMessageDao()
    {
        return iMMessageDao;
    }

    public IMConversationDao getIMConversationDao()
    {
        return iMConversationDao;
    }

    public IMAudioFailDao getIMAudioFailDao()
    {
        return iMAudioFailDao;
    }

    public IMVoiceGroupDao getIMVoiceGroupDao()
    {
        return iMVoiceGroupDao;
    }

    public IMCallLogDao getIMCallLogDao()
    {
        return iMCallLogDao;
    }

    public IMAddFriendDao getIMAddFriendDao()
    {
        return iMAddFriendDao;
    }

    public IMKeFuDao getIMKeFuDao()
    {
        return iMKeFuDao;
    }

    public IMWorkCircleDao getIMWorkCircleDao()
    {
        return iMWorkCircleDao;
    }

}
