package com.chaoxiang.entity.chat;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DDX_IM_ADD_FRIEND".
 */
public class IMAddFriend {

    private Long id;
    private String applicantMsgId;
    private String applicantTime;
    private String applicantId;
    private String applicantName;
    private String attached;
    private String workStatus;
    private String operateTime;
    private String icon;
    private String imAccount;
    private String attachment;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public IMAddFriend() {
    }

    public IMAddFriend(Long id) {
        this.id = id;
    }

    public IMAddFriend(Long id, String applicantMsgId, String applicantTime, String applicantId, String applicantName, String attached, String workStatus, String operateTime, String icon, String imAccount, String attachment) {
        this.id = id;
        this.applicantMsgId = applicantMsgId;
        this.applicantTime = applicantTime;
        this.applicantId = applicantId;
        this.applicantName = applicantName;
        this.attached = attached;
        this.workStatus = workStatus;
        this.operateTime = operateTime;
        this.icon = icon;
        this.imAccount = imAccount;
        this.attachment = attachment;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getApplicantMsgId() {
        return applicantMsgId;
    }

    public void setApplicantMsgId(String applicantMsgId) {
        this.applicantMsgId = applicantMsgId;
    }

    public String getApplicantTime() {
        return applicantTime;
    }

    public void setApplicantTime(String applicantTime) {
        this.applicantTime = applicantTime;
    }

    public String getApplicantId() {
        return applicantId;
    }

    public void setApplicantId(String applicantId) {
        this.applicantId = applicantId;
    }

    public String getApplicantName() {
        return applicantName;
    }

    public void setApplicantName(String applicantName) {
        this.applicantName = applicantName;
    }

    public String getAttached() {
        return attached;
    }

    public void setAttached(String attached) {
        this.attached = attached;
    }

    public String getWorkStatus() {
        return workStatus;
    }

    public void setWorkStatus(String workStatus) {
        this.workStatus = workStatus;
    }

    public String getOperateTime() {
        return operateTime;
    }

    public void setOperateTime(String operateTime) {
        this.operateTime = operateTime;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getImAccount() {
        return imAccount;
    }

    public void setImAccount(String imAccount) {
        this.imAccount = imAccount;
    }

    public String getAttachment() {
        return attachment;
    }

    public void setAttachment(String attachment) {
        this.attachment = attachment;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
