package com.chaoxiang.entity.chat;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DDX_IM_CALL_LOG".
 */
public class IMCallLog {

    private Long id;
    private String logId;
    private Integer answerType;
    private String fromImAccound;
    private String toImAccound;
    private String headUrl;
    private String withName;
    private Integer answerState;
    private Integer callMode;
    private Long createTime;
    private String attachment;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public IMCallLog() {
    }

    public IMCallLog(Long id) {
        this.id = id;
    }

    public IMCallLog(Long id, String logId, Integer answerType, String fromImAccound, String toImAccound, String headUrl, String withName, Integer answerState, Integer callMode, Long createTime, String attachment) {
        this.id = id;
        this.logId = logId;
        this.answerType = answerType;
        this.fromImAccound = fromImAccound;
        this.toImAccound = toImAccound;
        this.headUrl = headUrl;
        this.withName = withName;
        this.answerState = answerState;
        this.callMode = callMode;
        this.createTime = createTime;
        this.attachment = attachment;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLogId() {
        return logId;
    }

    public void setLogId(String logId) {
        this.logId = logId;
    }

    public Integer getAnswerType() {
        return answerType;
    }

    public void setAnswerType(Integer answerType) {
        this.answerType = answerType;
    }

    public String getFromImAccound() {
        return fromImAccound;
    }

    public void setFromImAccound(String fromImAccound) {
        this.fromImAccound = fromImAccound;
    }

    public String getToImAccound() {
        return toImAccound;
    }

    public void setToImAccound(String toImAccound) {
        this.toImAccound = toImAccound;
    }

    public String getHeadUrl() {
        return headUrl;
    }

    public void setHeadUrl(String headUrl) {
        this.headUrl = headUrl;
    }

    public String getWithName() {
        return withName;
    }

    public void setWithName(String withName) {
        this.withName = withName;
    }

    public Integer getAnswerState() {
        return answerState;
    }

    public void setAnswerState(Integer answerState) {
        this.answerState = answerState;
    }

    public Integer getCallMode() {
        return callMode;
    }

    public void setCallMode(Integer callMode) {
        this.callMode = callMode;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public String getAttachment() {
        return attachment;
    }

    public void setAttachment(String attachment) {
        this.attachment = attachment;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
