package com.chaoxiang.entity.chat;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DDX_IM_GROUP_CHAT".
 */
public class IMGroupChat {

    private Long id;
    private String groupId;
    private String userId;
    private Long joinTime;
    private String attachment;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public IMGroupChat() {
    }

    public IMGroupChat(Long id) {
        this.id = id;
    }

    public IMGroupChat(Long id, String groupId, String userId, Long joinTime, String attachment) {
        this.id = id;
        this.groupId = groupId;
        this.userId = userId;
        this.joinTime = joinTime;
        this.attachment = attachment;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Long getJoinTime() {
        return joinTime;
    }

    public void setJoinTime(Long joinTime) {
        this.joinTime = joinTime;
    }

    public String getAttachment() {
        return attachment;
    }

    public void setAttachment(String attachment) {
        this.attachment = attachment;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
