package com.chaoxiang.entity.chat;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DDX_IM_KEFU".
 */
public class IMKeFu {

    private Long id;
    private String icon;
    private String realName;
    private String sex;
    private String dpName;
    private String job;
    private String userType;
    private String email;
    private String telephone;
    private String userId;
    private String imAccount;
    private String account;
    private String attachment;
    private String phone;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public IMKeFu() {
    }

    public IMKeFu(Long id) {
        this.id = id;
    }

    public IMKeFu(Long id, String icon, String realName, String sex, String dpName, String job, String userType, String email, String telephone, String userId, String imAccount, String account, String attachment) {
        this.id = id;
        this.icon = icon;
        this.realName = realName;
        this.sex = sex;
        this.dpName = dpName;
        this.job = job;
        this.userType = userType;
        this.email = email;
        this.telephone = telephone;
        this.userId = userId;
        this.imAccount = imAccount;
        this.account = account;
        this.attachment = attachment;
    }

    public String getPhone()
    {
        return phone;
    }

    public void setPhone(String phone)
    {
        this.phone = phone;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getRealName() {
        return realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getDpName() {
        return dpName;
    }

    public void setDpName(String dpName) {
        this.dpName = dpName;
    }

    public String getJob() {
        return job;
    }

    public void setJob(String job) {
        this.job = job;
    }

    public String getUserType() {
        return userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getImAccount() {
        return imAccount;
    }

    public void setImAccount(String imAccount) {
        this.imAccount = imAccount;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getAttachment() {
        return attachment;
    }

    public void setAttachment(String attachment) {
        this.attachment = attachment;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
