package com.chaoxiang.entity.chat;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DDX_IM_CIRCLE".
 */
public class IMWorkCircle {

    private Long id;
    private String type;
    private String from;
    private String btype;
    private String remark;
    private String circleId;
    private String userId;
    private String userName;
    private String icon;
    private String title;
    private String attachment;
    private String createTime;
    private String messageId;
    private int unReadMsg;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public IMWorkCircle() {
    }

    public IMWorkCircle(Long id) {
        this.id = id;
    }

    public IMWorkCircle(Long id, String type, String from, String btype, String remark, String circleId, String userId, String userName, String icon, String title, String attachment, String createTime, String messageId, int unReadMsg) {
        this.id = id;
        this.type = type;
        this.from = from;
        this.btype = btype;
        this.remark = remark;
        this.circleId = circleId;
        this.userId = userId;
        this.userName = userName;
        this.icon = icon;
        this.title = title;
        this.attachment = attachment;
        this.createTime = createTime;
        this.messageId = messageId;
        this.unReadMsg = unReadMsg;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getFrom() {
        return from;
    }

    public void setFrom(String from) {
        this.from = from;
    }

    public String getBtype() {
        return btype;
    }

    public void setBtype(String btype) {
        this.btype = btype;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getCircleId() {
        return circleId;
    }

    public void setCircleId(String circleId) {
        this.circleId = circleId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAttachment() {
        return attachment;
    }

    public void setAttachment(String attachment) {
        this.attachment = attachment;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getMessageId() {
        return messageId;
    }

    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    public int getUnReadMsg() {
        return unReadMsg;
    }

    public void setUnReadMsg(int unReadMsg) {
        this.unReadMsg = unReadMsg;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
