package com.chaoxiang.entity.group;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DDX_IM_GROUP".
 */
public class IMGroup {

    private String groupId;
    private String groupName;
    private String companyId;
    private String owner;
    private Long joinTime;
    private String createTime;
    private String updateTime;
    private String memberStringList;
    private Integer groupType;
    private Long createTimeMillisecond;
    private Long updateTimeMillisecond;
    private String attachment;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public IMGroup() {
    }

    public IMGroup(String groupId) {
        this.groupId = groupId;
    }

    public IMGroup(String groupId, String groupName, String companyId, String owner, Long joinTime, String createTime, String updateTime, String memberStringList, Integer groupType, Long createTimeMillisecond, Long updateTimeMillisecond, String attachment) {
        this.groupId = groupId;
        this.groupName = groupName;
        this.companyId = companyId;
        this.owner = owner;
        this.joinTime = joinTime;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.memberStringList = memberStringList;
        this.groupType = groupType;
        this.createTimeMillisecond = createTimeMillisecond;
        this.updateTimeMillisecond = updateTimeMillisecond;
        this.attachment = attachment;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public String getCompanyId() {
        return companyId;
    }

    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public Long getJoinTime() {
        return joinTime;
    }

    public void setJoinTime(Long joinTime) {
        this.joinTime = joinTime;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    public String  getMemberStringList() {
        return memberStringList;
    }

    public void setMemberStringList(String memberStringList) {
        this.memberStringList = memberStringList;
    }

    public Integer getGroupType() {
        return groupType;
    }

    public void setGroupType(Integer groupType) {
        this.groupType = groupType;
    }

    public Long getCreateTimeMillisecond() {
        return createTimeMillisecond;
    }

    public void setCreateTimeMillisecond(Long createTimeMillisecond) {
        this.createTimeMillisecond = createTimeMillisecond;
    }

    public Long getUpdateTimeMillisecond() {
        return updateTimeMillisecond;
    }

    public void setUpdateTimeMillisecond(Long updateTimeMillisecond) {
        this.updateTimeMillisecond = updateTimeMillisecond;
    }

    public String getAttachment() {
        return attachment;
    }

    public void setAttachment(String attachment) {
        this.attachment = attachment;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
